source 'https://rubygems.org'

ruby '2.0.0'

gem 'rails', '>= 4.0.0'

gem 'bunny', ">= 0.9.1"
gem 'dotenv-rails'
gem 'haml'
gem 'httparty'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-datatables-rails'
gem 'less-rails'
gem 'poro_plus'
gem 'therubyracer'
gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git', :branch => 'bootstrap3'

group :assets do
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'sass-rails'
end

group :development do
  gem 'unicorn'
  gem 'hpricot'
  gem 'ruby_parser'
#  gem 'rack-mini-profiler'
end

group :test do
  gem 'rspec-rails'
end